model_name: "clip-ViT-B-16"
test_images_folder: "test/imags"
train_images_folder: "train/imgs"
emb_output_folder: "weights/embed"
train_labels_folder: "train/labels"
train_labels_with_text_folder: "train/labels_with_text"
output_excel: "results.xlsx"
n_neighbors: 10
threshold: 33.8